// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/google/wire"
	"wire-example/internal/order"
	"wire-example/internal/user"
	"wire-example/pkg/cron"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	database, err := NewDatabase()
	if err != nil {
		return nil, err
	}
	iCache := NewCache()
	module := user.InitModule(database, iCache)
	service := order.NewOrderService(database, iCache)
	handler := module.Handler
	engine := NewGinServer(handler)
	cronCron := &cron.Cron{
		Cache: iCache,
	}
	app := &App{
		userModule:   module,
		orderService: service,
		ginServer:    engine,
		cron:         cronCron,
	}
	return app, nil
}

// wire.go:

var BaseSet = wire.NewSet(NewDatabase, NewCache)
