// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"sync"
	"wire-example/internal/user/repository"
	"wire-example/internal/user/service"
	"wire-example/internal/user/web"
	"wire-example/pkg/cache"
	"wire-example/pkg/db"
)

// Injectors from wire.go:

// InitModule 要是 db 和 cache 这两个依赖不在 user 包下，则需要从外面引入，需要放入到这个方法参数下
func InitModule(db2 *db.Database, cache2 cache.ICache) *Module {
	service := InitService(db2)
	handler := InitHandler(service)
	module := &Module{
		Handler: handler,
		Svc:     service,
		Cache:   cache2,
	}
	return module
}

func InitHandler(service2 service.Service) *web.Handler {
	handler := web.NewHandler(service2)
	return handler
}

// wire.go:

type (
	Handler = web.Handler
	Service = service.Service
)

func InitUserRepo(db2 *db.Database) repository.UserRepository {
	return repository.NewUserRepository(db2)
}

var (
	once = &sync.Once{}
	svc  service.Service
)

func InitService(db2 *db.Database) service.Service {
	once.Do(func() {
		orderRepository := repository.NewUserRepository(db2)
		svc = service.NewService(orderRepository)
	})
	return svc
}
